### ISSUE TITLE
Hashes should not be platform dependent

### ISSUE THREAD

**Issue by bannmann** [phxql/argon2-jvm#10]
As `BaseArgon2` uses [String.getBytes()](http://docs.oracle.com/javase/8/docs/api/java/lang/String.html#getBytes--) within `hash()` and `verify()`, the input to Argon2 and thus the results depend on the platform default encoding, which is different on Linux (UTF-8) and Windows (Windows-1252).

This is a classic error that leads to Windows developer machines not being able to verify passwords created by Linux production servers.

**Comment by phxql** [comment]
See this PR: https://github.com/phxql/argon2-jvm/pull/1

**Comment by GrmpCerber** [comment]
Sorry to bother you with that @phxql  but IMHO having a deterministic code in password management is mandatory.
I think there is two ways to achieve this : allow the developer to choose a charset or impose a fixed one.
In the first scenario this would require us to add a new parameter inside the hash (to be able to verify the password with the correct charset). Yet this seems impractical as this section is managed by the C lib. 
The other scenario would be to use a fixed charset like UTF-8.
Both lead to a retrocompatibility problem : how to deal with old passwords ?
Break retrocompatibility ? 
try both charsets (hence doubling the cost) ?
Add extra data to the hashing output to be able to differentiate old algorithm from the new one ?

**Comment by phxql** [comment]
Hi,

i've added overloads to hash and verify to accept a `Charset`. I also decided to break compatibility and noted that in the changelog: The default charset is now UTF-8.
