### ISSUE TITLE
UnsatisfiedLinkError on Windows

### ISSUE THREAD

**Issue by pratnala** [phxql/argon2-jvm#11]
I included the dependency in my `pom.xml` in a normal Java project file but calling any argon2 function (hash for example) gives an UnsatisfiedLinkError. Are any libraries missing? Same error when included  via Gradle for an Android app as well ([see this too](http://stackoverflow.com/q/37912874/1416629))

**Comment by phxql** [comment]
On Windows it should work, will test it.

Your android is ARM architecture, isn't it? This library doesn't include ARM-compiled binaries of the Argon2 C library.

**Comment by pratnala** [comment]
This is what I get in a normal, simple Java app made in IntelliJ

`Exception in thread "main" java.lang.UnsatisfiedLinkError: The specified module could not be found.`

Moreover, so there is no hope of running this on Android?

**Comment by phxql** [comment]
It doesn't run on Android in the current version, no. You can try to compile libargon on ARM for yourself.
