### ISSUE TITLE
MSYS2 dependency

### ISSUE THREAD

**Issue by Qowyn** [phxql/argon2-jvm#12]
Documentation should mention the dependency on MSYS2 for windows.

Even after installing MSYS2 from https://msys2.github.io/ and adding \usr\bin to the path the library either crashes on use or seems to be stuck in an infinite loop.

OS: Windows 10

**Comment by phxql** [comment]
Oh, I didn't want to introduce a dependency to MSYS. Now I have to find a way to compile the Argon2 lib for windows without a dependency on MSYS.

**Comment by Qowyn** [comment]
Since the current DLLs don't work for me I made a fork for this: https://github.com/Qowyn/phc-winner-argon2

Includes VS2015 Projects that generate DLLs, can be compiled using just [MSBuild](https://www.microsoft.com/de-de/download/details.aspx?id=48159) + [Visual C++](http://landinghub.visualstudio.com/visual-cpp-build-tools)

`msbuild /p:Configuration=ReleaseStatic`

The resulting DLL works like a charm

**Comment by phxql** [comment]
Nice, thank you! I'll integrate those DLLs in the project.

**Comment by phxql** [comment]
Fixed with v2.0.
