### ISSUE TITLE
not working on OSX

### ISSUE THREAD

**Issue by menzus** [phxql/argon2-jvm#16]
Hi,

The current libargon.dylib doesn't work for me, it's complaining because of the missing argon2_encodedlen.

I've rebuilt libargon.dylib lib locally and your lib works fine with that lib.

Thanks for the lib!
Tamas

**Comment by menzus** [comment]
I just saw that you already updated it on develop!

when are you planning to release it?

**Comment by mattes3** [comment]
Same thing here on my OSX machine. I would also be interested in a new release. My development platform is Mac OS X:

```
$ uname -a
Darwin ... 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64
```
My deployment platform is Ubuntu Linux:
```
$ uname -a
Linux ... 3.13.0-95-generic #142-Ubuntu SMP Fri Aug 12 17:00:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by menzus** [comment]
Currently I'm using the released version, I've compiled the dylib (https://github.com/phxql/argon2-jvm/blob/master/docs/compile-argon2.md) and placed in into my projects resources/darwin folder. 
JNA searches for it there before it looks into jars.

You can do the same thing with the libargon2.so (https://packages.debian.org/sid/libargon2-0).

It could be useful to split the project into different libs, like a core without any precompiled binary libs.

As it's a security lib, people might want to compile it for themselves or get it from some trusted repository rather than from a jar.

**Comment by phxql** [comment]
Should be fixed with v2.0, i just released it.

**Comment by menzus** [comment]
thanks, it works fine on mac!

have you considered to have a lib without the precompiled binaries?

**Comment by phxql** [comment]
I'll create a new ticket for this :)
