### ISSUE TITLE
nul chars at end of hash

### ISSUE THREAD

**Issue by naude-r** [phxql/argon2-jvm#2]
the library currently allocates a fixed size buffer of HASH_LENGTH * 4. this is a bit wasteful. the updated argon2 c library provides an api to query the actual length needed, argon2_encodedlen.

the returned hash still contains 3 nul chars. not sure why, but probably because the library overestimate the length.

these can be safely ignored. the reason for this is that the hash is not safe for insertion into e.g. a db as utf-8 does not allow nul chars. changing the encoding is not really an option either.

**Comment by phxql** [comment]
Done. Thanks!
