### ISSUE TITLE
Problem when switching algorithms

### ISSUE THREAD

**Issue by mattes3** [phxql/argon2-jvm#20]
I switched from Argon2i to Argon2d today. The problem is that old password hashes cannot be verified any more. This is wrong.

Resolution:
The method Argon2.verify() must inspect the hash, detect the algorithm that it was created with, and then use that algorithm automatically. You can see the word "$argon2i" as part of the hash code, so this should be easy to do.

**Comment by phxql** [comment]
Hi,

If you use Argon2d to verify Argon2i hashes, it will fail:

```java
        Argon2 argon2i = Argon2Factory.create(Argon2Factory.Argon2Types.ARGON2i);
        String argon2iHash = argon2i.hash(1, 65535, 1, "Test");
        System.out.println(argon2iHash);
        assert argon2i.verify(argon2iHash, "Test");

        Argon2 argon2d = Argon2Factory.create(Argon2Factory.Argon2Types.ARGON2d);
        String argon2dHash = argon2d.hash(1, 65535, 1, "Test");
        System.out.println(argon2dHash);
        assert argon2d.verify(argon2dHash, "Test");

        // That won't work, use a Argon2i instance to verify argon2i hashes
        assert argon2d.verify(argon2iHash, "Test");
        // That won't work, use a Argon2d instance to verify argon2d hashes
        assert argon2i.verify(argon2dHash, "Test");
```

It's your responsibility to use the correct instance to compare the hashes.

**Comment by saisubramaniam** [comment]
Hi,

I am getting results when I try to hash using Argon2(both i and d)

This is what I get..

> SALT:d94eaa2ae725c26494853167782ab21fba7e75954e3617645ed89de92f7d294f
> Verification step: Doesnt Match
> HASH:$argon2d$v=19$m=100,t=1,p=1$Q2qDBVg939PYXLvVMMllEg$8x99qzkeTdEA2DphpUgb03OnEPnJ/dr+GFB9cUJha3E

src:
```
Argon2 argon2 = Argon2Factory.create(Argon2Factory.Argon2Types.ARGON2d);
char[] password = (passwd+ salt).toCharArray();
String hash = argon2.hash(1, 100, 1, password);
System.out.print("Verification step:");
if (argon2.verify(hash, password)) {
     System.out.println("Matches");
} else {
     System.out.println("Doesnt Match");
}
```

Can you pls help me figure out why the verification fails?

Thanks.
