### ISSUE TITLE
The example code does not work

### ISSUE THREAD

**Issue by PH0lder** [phxql/argon2-jvm#22]
I copied the example code off the front page and dropped it into a new project to begin testing, and it failed immediately with a "Does not match."  After some playing around, I found that the issue was that the input password appears to be modified by the hash step, so it's not useful for the verify step.  I changed the code to be the following, and it started working.  I think you should comment on this fact in the example (for example  // password is erased by hash step ) or something similar.

```
package crypto.testing.argon2;

import de.mkammerer.argon2.Argon2;
import de.mkammerer.argon2.Argon2Factory;

final class Argon2Test
{
  public static void doTest()
  {
    final Argon2 argon2 = Argon2Factory.create();

    char[] password = { 'P', 'a', 's', 's', 'w', 'o', 'r', 'd' };  // password is erased by hash step
    char[] password2 = { 'P', 'a', 's', 's', 'w', 'o', 'r', 'd' };

    try
    {
      final String hash = argon2.hash(2, 65536, 1, password);
      if (argon2.verify(hash, password2))
      {
        System.out.println("Matches");
      }
      else
      {
        System.out.println("Doesn't Match");
      }
    }
    finally
    {
      argon2.wipeArray(password);
      argon2.wipeArray(password2);
    }
  }
}
```

**Comment by phxql** [comment]
Thanks for the ticket. Indeed, the `hash` method wipes the given array.

**Comment by phxql** [comment]
Fixed the bug in develop branch, will close the bug once it's merged in master.
