### ISSUE TITLE
How should I store a hashed password ?

### ISSUE THREAD

**Issue by pauloricardopr** [phxql/argon2-jvm#28]
Hi,

I want to store a hashed combination of 2 _identifiers_ like (1234567890 + BC123) using the result of `hash` method. Example:

`$argon2i$v=19$m=64,t=1,p=2$c3XlfbsarR7+E4Di+q2j4Q$eOPC6mVEO62Xh04r+owM1ATMAzB6Zzx/0lxWtLS/aaE`

I need to check this combination but I'm not comfortable with this format because it shows some of parameters I have used >> `$argon2i$v=19$m=64,t=1,p=2`

How should I use a raw hashed password using Argon2-jvm ? Can I omit those parameters ? 

Thank you in advance!

**Comment by phxql** [comment]
These parameters aren't secret, so you can store them. That way the hash is self-describing and contains all the data needed for verification. If you really don't want these parameters in your hash, you can use the `rawHash` methods to get a raw hash, which you have to compare by yourself (see the test `de.mkammerer.argon2.test.LibraryTest#testArgon2dRawHash` in `develop` branch).

**Comment by phxql** [comment]
Can i close this issue?

**Comment by FloatingSunfish** [comment]
_>These parameters aren't secret, so you can store them._
@phxql Could you provide a link that I can use as proof for this? Might help explain why we can and should store these values.

And many thanks for making such a great library! :)

**Comment by phxql** [comment]
Sure, here for example: https://crypto.stackexchange.com/questions/43471/storing-parameters-in-argon2-hash-as-potential-security-issue

**Comment by FloatingSunfish** [comment]
@phxql Noted, thanks! :)
