### ISSUE TITLE
Argon2 error

### ISSUE THREAD

**Issue by MallaAditya** [phxql/argon2-jvm#29]
When I try to execute my application which contains Argon2 hashing, am getting the below exception
**java.lang.NoClassDefFoundError: Could not initialize class de.mkammerer.argon2.jna.Argon2Library**
Can anyone help me on this?
Thank you

**Comment by phxql** [comment]
On which architecture (x64, arm, etc.) and OS (windows, linux, osx) is this?

**Comment by MallaAditya** [comment]
Hello @phxql 
We are using x64 and Red Hat Linux.

**Comment by MallaAditya** [comment]
Hello @phxql 
We are using x64 and Red Hat Linux.

**Comment by phxql** [comment]
You are using the library with the precompiled libraries, not the `-nolibs`, right?

**Comment by MallaAditya** [comment]
Yes @phxql ... the dependencies are loaded through pom xml, In my local machine am able to run the application with out any errors, but after deploying the war file in tomcat 8.0.46 am getting NoClassDeffoundError..

**Comment by phxql** [comment]
It could be that Tomcat mangles the classpath of the JAR somehow. JNA tries to load the .so file from the classpath under `linux-x86-64/libargon2.so`. I fear that i can't help on that issue, I have not that much expertise in Java application server and classpathes. Maybe googling for "Tomcat JNA" or "Tomcat JNI" could help?

**Comment by phxql** [comment]
If you find a solution, can you please report back so I can include that in some documentation? Thanks!

**Comment by george-007** [comment]
@MallaAditya which version of Red Hat Linux do you use? We had the same error on centos 6. On centos 7 the library works.

**Comment by MallaAditya** [comment]
@george-007 we are using 6.5 version..
@phxql for sure we will report you back if we can get a solution for that..

**Comment by george-007** [comment]
Is your local machine where the library works also running rhel 6.5? If not maybe compiling your own argon library binary https://github.com/phxql/argon2-jvm/blob/master/docs/compile-argon2.md on the rhel 6.5 machine could help (maybe different versions of system libraries like libc, ... are needed on rhel 6).

**Comment by phxql** [comment]
Another idea would be to use the `-nolibs` artifact and install libargon2 via package manager.

**Comment by phxql** [comment]
@MallaAditya Any news on this?

**Comment by kosprov** [comment]
From `com.sun.jna.Native` javadoc:

> If your system has additional security constraints regarding execution or load of files (SELinux, for example), you should  probably install the native library in an accessible location and configure  your system accordingly, rather than relying on JNA to extract the library  from its own jar file.

Maybe it has to do something with SELinux.

**Comment by phxql** [comment]
On my Fedora 27, SElinux is enabled, and Argon2-JVM 2.3 is working fine:

```
$ /usr/sbin/sestatus                                                         
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      31
```

**Comment by phxql** [comment]
You could try running https://github.com/phxql/jna-info

This small tool will test jna by invoking the printf function. If that fails, JNA is to blame. Otherwise its a problem of the argon2-jvm code.

**Comment by Rahsmi** [comment]
I came across this issue when was finding a way to solve the

**java.lang.NoClassDefFoundError: Could not initialize class de.mkammerer.argon2.jna.Argon2Library**

I had the latest (at this moment) release of JNA library in my project: **JNA 5.3.x**. Have to warn, that 5.**3**.x version of JNA is **not** compatible with this argon2-jvm implementation. I had to fallback to JNA 5.**2**.x and it works just perfect with it.

**Comment by alterunuvu** [comment]
Greetings, 2022
java.lang.ClassNotFoundException: de.mkammerer.argon2.Argon2Factory$Argon2Types

Any solution about this?
I have installed Argon2 using Maven dependency and doesn´t work.

Thanks
