### ISSUE TITLE
java.lang.UnsatisfiedLinkError Exception

### ISSUE THREAD

**Issue by Joseph-Maria** [phxql/argon2-jvm#30]
I'm getting "Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\username\AppData\Local\Temp\jna--1431697088\jna1323202483558456767.dll: Can't find dependent libraries" When i try to run my application which is using Argon2. 
I have tried both the libraries with pre-compiled Argon2 libraries and the one without pre-compiled Argon2 libraries and got same issue.
What should i do to fix this issue?
Thanks you!!!

**Comment by phxql** [comment]
I assume this is windows? Which architecture (x86, x64, arm...) etc?

**Comment by Joseph-Maria** [comment]
Yes, it's windows. I'm using x64 architecture and Java 9.0.1.
I have tried JNA version 4.5.0 instead of current version coming with Argon2, and it run well with the pre-compiled Argon2 libraries. I don't know why, but the issue seem to be fixed.

**Comment by phxql** [comment]
thanks for the headsup, maybe a Java 9 problem. I'll update JNA.

**Comment by phxql** [comment]
Huh? Argon2 comes with JNA 4.5.0:

`compile 'net.java.dev.jna:jna:4.5.0'`

Maybe you have a version conflict in your project?

**Comment by Joseph-Maria** [comment]
You are welcome.

**Comment by phxql** [comment]
Just released v2.3 with the newest JNA version
