### ISSUE TITLE
Argon2 failed to create temporary file?

### ISSUE THREAD

**Issue by camdenorrb** [phxql/argon2-jvm#32]
Ello, I was planning on utilizing Argon2 JVM bindings on my server. But it appears to be having some issues on load, any help or questions are appreciated :)

I followed the casual setup for adding Argon as a dependency in Gradle:
`compile "de.mkammerer:argon2-jvm:2.3"`

#### Error: https://pastebin.com/sh5invAB

**Comment by phxql** [comment]
Which architecture, operating system and Java version is this?

**Comment by camdenorrb** [comment]
@phxql x86-64, Windows 10, Java 9

**Comment by camdenorrb** [comment]
I ran it in Java 8 and it appears to run fine.

**Comment by phxql** [comment]
I'll test it with Java 9.

**Comment by phxql** [comment]
I created a small Java 9 project, using 
```xml
        <dependency>
            <groupId>de.mkammerer</groupId>
            <artifactId>argon2-jvm</artifactId>
            <version>2.3</version>
        </dependency>
```

and the `module-info.java`:

```java
module test {
    requires argon2.jvm;
}
```

and run it with `/usr/lib/jvm/java-9/bin/java -p /home/moe/tmp/test/target/classes:/home/moe/.m2/repository/de/mkammerer/argon2-jvm/2.3/argon2-jvm-2.3.jar:/home/moe/.m2/repository/net/java/dev/jna/jna/4.5.0/jna-4.5.0.jar -m test/test.Main`

and this works.

```
java -version
openjdk version "9.0.1"
OpenJDK Runtime Environment (build 9.0.1+11)
OpenJDK 64-Bit Server VM (build 9.0.1+11, mixed mode)
```

x64, Linux, Fedora 27

**Comment by phxql** [comment]
You could try running https://github.com/phxql/jna-info

This small tool will test jna by invoking the printf function. If that fails, JNA is to blame. Otherwise its a problem of the argon2-jvm code.
