### ISSUE TITLE
Linux-ARM ?

### ISSUE THREAD

**Issue by maximeozenne** [phxql/argon2-jvm#33]
Hello,

I based all my website's security around your argon2 library for the jvm. it worked really great on my development computer but now I tried to push all on my server (rpi2 arm architecture) and I have the following error : 

>  Unable to load library 'argon2': Native library (linux-arm/libargon2.so) not found

Are you planning to make an arm version ?

**Comment by phxql** [comment]
You could try to install argon2 from your linux distribution.

If I find the time, I'll compile an Argon2 on my Raspi 2 and add it.

**Comment by phxql** [comment]
I added support for Linux ARM in 85b894a9a3868784f6556aabce10775097905d42. The next release will include it.

**Comment by maximeozenne** [comment]
Thank you !
