### ISSUE TITLE
Compile Argon2 on a Raspi 3 (Arm 64 Bit)

### ISSUE THREAD

**Issue by phxql** [phxql/argon2-jvm#34]
It would be great if someone who owns a Raspberry Pi 3 could compile Argon2 on a 64 Bit ARM Linux and provide me the libargon2.so file.

Steps:

1. Download the source from https://github.com/P-H-C/phc-winner-argon2/releases/tag/20161029
2. Extract source
3. Run `make clean && make`
4. Upload the libargon2.so somewhere (or send it to me via email)
5. Comment this ticket

Thanks a lot!

**Comment by Gatgeagent** [comment]
https://transfer.sh/47ocC/libargon2.so

**Comment by phxql** [comment]
Thanks!

**Comment by nemoryoliver** [comment]
> https://transfer.sh/47ocC/libargon2.so

still have a copy of this?

**Comment by phxql** [comment]
Yep, it's this one: https://github.com/phxql/argon2-jvm/tree/master/argon2-jvm/src/main/resources/linux-aarch64
