### ISSUE TITLE
Reusing an argon2 instance

### ISSUE THREAD

**Issue by sonOfRa** [phxql/argon2-jvm#35]
Hello,

are argon2 instances created by the factory safe for hashing multiple passwords, or should a new instance be created everytime I need to hash a new password?

**Comment by phxql** [comment]
They are threadsafe, you can reuse the instances.

**Comment by sonOfRa** [comment]
Thank you!

**Comment by phxql** [comment]
I'll add a comment in the JavaDoc of the classes.

**Comment by jibbers42** [comment]
I think a note in the readme would be helpful too. It took me a bit a find this and those classes aren't really used directly so I didn't notice the javadocs in the IDE.

Also, if I were to use two instances at once in separate threads, do you know if they would run at the same time or would the underlying library would force one to wait?

**Comment by phxql** [comment]
The library uses JNI to invoke the C library. I have no idea if the C library uses a mutex or any other synchronization mechanism, but my assumption is that it does not. The argon2-jvm library has no mutex and should be fully parallelizable.
