### ISSUE TITLE
Java 9 Modules

### ISSUE THREAD

**Issue by sonOfRa** [phxql/argon2-jvm#39]
Hi,
while it's probably not reasonable to ask for full java9 module-info.java style module support, do you think it would be possible to add an Automatic-Module-Name entry to the Manifest of the released jars? This allows people who are using java9 to specify that name as a module dependency, as long as modules aren't fully supported by the library itself.

Module names are like package names, so a reasonable Automatic-Module-Name entry in the Manifest would look like ``Automatic-Module-Name: de.mkammerer.argon2``. Technically, automatic module names can also be inferred from the name of the .jar that supplies the module. This is impossible with maven however, because maven .jar files are always named like ``artifactId-${project.version}.jar``. Since dashes are illegal in module names, a .jar used by maven can never be used to infer an automatic module name.

EDIT:
Apparently I *can* acquire an automatic module name, and it's derived as "argon2.jvm". However, maven strongly advises me not to publish such an artifact, which makes sense, since the module name might change, and that will break the software in the future.

**Comment by phxql** [comment]
There is already a commit on the develop branch, 79a38129299a67f46caab39d7455f30f22ae6d29, which adds Automatic-Module-Name. Is this sufficient?

**Comment by sonOfRa** [comment]
Ah, I didn't see this. Yes, that'll work. I'll close #40 then.

**Comment by phxql** [comment]
Okay. Thanks for you work, anyway! Always appreciated. :)
