### ISSUE TITLE
Argon2 library update process

### ISSUE THREAD

**Issue by righettod** [phxql/argon2-jvm#43]
Hello,

First thanks you very much for this project :smiley:

What is your internal process about updating the version of the argon2 library bring with the version of the project with pre-compiled libraries ?

I ask the question in order to know if you will sync your release process on the one followed by https://github.com/P-H-C/phc-winner-argon2 ...

Thanks you in advance and thanks you again for this binding.

**Comment by phxql** [comment]
Hi,

there is unfortunately no automated update process. I sometimes check the releases page from the linked GitHub repository. I can compile the libraries for Windows, Linux and ARM-32 without problems, but to compile it on MacOS and ARM-64 I need some help, as I don't own compatible platforms.

As far as I know, the Argon2 project doesn't provide precompiled libraries.

**Comment by righettod** [comment]
Hi,

Thanks you very much for your response.

I have tested the project on Windows with the release 20171227 of the PHC release compile with VS2017 and is ok.

Thanks again for your project :)
