### ISSUE TITLE
String returning method with salt

### ISSUE THREAD

**Issue by uded** [phxql/argon2-jvm#45]
As noted in #19 it would be beneficial to have a `de.mkammerer.argon2.Argon2Advanced#hash(int, int, int, char[], java.nio.charset.Charset, byte[])` and similar families of functions returning not only a `byte[]` hash but also String encoded value, in a form similar to `$argon2i$v=19$m=8,t=12,p=1$c29tZXNhbHQ$ZzPm92ZR51LG5FN5bQQBl5nS2mdvKeqFUWVQW0RZujA`. This can be used for variety of situations, including testing, etc.

**Comment by phxql** [comment]
I added a new method in f84fe1271212cde48e115c16c1c254f6a72bfebd. Is that what you need?
