### ISSUE TITLE
Verify fails randomly on correct password

### ISSUE THREAD

**Issue by ssaarinen** [phxql/argon2-jvm#46]
I tested the library (2.4 with precompiled libraries) a bit to get a hang of it. When generating and verifying hashes I managed to create a few that randomly fail to verify against the right password. Below is the code for verifying one such hash.

```
public static void main(String[] args) {
    Argon2 argon2 = Argon2Factory.create();
    char[] pw  = "asdf1234".toCharArray();

    String[] hash2 = {
            "$argon2i$v=19$m=65536,t=50,p=2$vXgi/gv6esyrWW0nuGhHwQ$q0Sr90J719a5WhDXQQXir/jUP200CZ6hqGErUiQhYIc"
    };

    for(int i = 0; i < 1000; i++) {
        for (String s : hash2) {
            boolean verify2 = argon2.verify(s, pw);
            System.out.println(i+ ": " + verify2);
        }
    }
}
```

On my testing it fails pretty randomly but maybe 1/10 of the time. But sometimes more often as can be seen below.

Couple of sample runs:
```
0: true
1: true
2: true
3: true
4: true
5: false
6: false
7: true
8: true
9: true
10: true
11: true
12: false
13: true
```

```
0: true
1: true
2: true
3: false
4: true
5: false
6: true
7: true
8: true
9: false
10: false
```

**Comment by phxql** [comment]
Which operating system and bitness?

**Comment by ssaarinen** [comment]
windows 10 x64

**Comment by phxql** [comment]
That's really strange. I just tested it on my machine (Linux x64), all verify calls are returning true. Will test that on Windows, too.

**Comment by ssaarinen** [comment]
I just found out that my PC has foulty memory. Its likely causing this.
I'll let you know but don't waste time on this just yet :)

ma 26. helmik. 2018 klo 11.36 Moritz Kammerer <notifications@github.com>
kirjoitti:

**Comment by phxql** [comment]
Okay.

**Comment by ssaarinen** [comment]
That seems to be it. I got rid of the faulty memory and now verifying got to 100 rounds without failures so I think this can be closed. Sorry for the trouble.

**Comment by phxql** [comment]
No problem.
