### ISSUE TITLE
JNA Method not Found

### ISSUE THREAD

**Issue by tuanpham91** [phxql/argon2-jvm#50]
Sorry If this question not appropriate here, but i used the no-libs version, try to hash something and results into this exception

java.lang.NoSuchMethodError: com.sun.jna.IntegerType.<init>(IJZ)V

	at de.mkammerer.argon2.jna.JnaUint32.<init>(JnaUint32.java:22)

What did i do wrong here ? I added the maven dependencies and thats it, i did nothing more. I use windows 7 64bit

**Comment by phxql** [comment]
Hi,

which JDK version?

**Comment by tuanpham91** [comment]
Hi, 

my current JDK-Version is 1.8.0_161.

**Comment by phxql** [comment]
Can you give me the exact version of JNA you're using? For example by running `mvn dependency:tree | grep net.java.dev.jna`.

**Comment by tuanpham91** [comment]
The version  of JNA is 4.5.1

**Comment by phxql** [comment]
I have no idea what is causing this. Is this a bigger codebase or a playground project? I just tested it with

```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>de.mkammerer</groupId>
                <artifactId>argon2-jvm</artifactId>
                <version>2.4</version>
            </dependency>

            <dependency>
                <groupId>net.java.dev.jna</groupId>
                <artifactId>jna</artifactId>
                <version>4.5.1</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

and it works.

**Comment by tuanpham91** [comment]
Could it be a dependency conflict with glassfish ? Because this is a glassfish project, i just added  the jna-4.5.1.

**Comment by phxql** [comment]
I have never tested the library inside an application server. These servers do all funny kind of stuff to the classloaders, so maybe that's a general problem with application servers.

**Comment by phxql** [comment]
This seems like a similiar issue: https://github.com/oshi/oshi/issues/144

**Comment by phxql** [comment]
@tuanpham91 Any news on this?

**Comment by tuanpham91** [comment]
@phxql We chose another algorithm. The last time i tried it still didnt work.

**Comment by phxql** [comment]
Ok, thanks for the update.
