### ISSUE TITLE
Consider Apache 2.0 License?

### ISSUE THREAD

**Issue by rwinch** [phxql/argon2-jvm#51]
I'm the project lead for [Spring Security](https://projects.spring.io/spring-security/). We would like to [provide integration with argon2](https://github.com/spring-projects/spring-security/issues/5354). The argone2-jvm [license](https://github.com/phxql/argon2-jvm#license) of LGPL v3 is [not compatible](https://www.apache.org/licenses/GPL-compatibility.html) to allow it to be used with an Apache 2.0 (our license) licensed project. Would you consider licensing it under Apache 2.0 or another compatible license as well?

**Comment by phxql** [comment]
Hi, i'm honored that you consider this library in such a big project like Spring Security, but unfortunately I won't relicense the library under Apache 2.0 or anything compatible. I chose the copyleft part of the LGPL explicitly.

Maybe you could use https://github.com/kosprov/jargon2-api ?

**Comment by rwinch** [comment]
@phxql Thanks for the response and the pointer. I will look into using jargon2-api
