### ISSUE TITLE
Add method to check if a hashed password should be rehashed

### ISSUE THREAD

**Issue by LordMonoxide** [phxql/argon2-jvm#56]
As time goes on you may need to increase your hashing parameters.  Old hashes you still have stored should be rehashed at this point, but can only be rehashed when the original password is available.  Consider something like this:

```
pwHash = db->get();
pw = input->get();

if(argon->verify(pwHash, pw)) {
  if(argon->needsRehash(pwHash)) {
    pwHash = argon->hash(...);
    db->update();
  }

  this->login();
}
```

**Comment by sephiroth-j** [comment]
A simple `needsRehash(owd)`method will not work - one has to provide at least the same cost factors as for the `hash` method. A _naive_ approach could be as follows:

1. extract the cost factors from the provided hash (_actual_) and compare them to provided factors (_expected_). 
1. return `false` if all actual factors are greater than or equal to their expected counterparts.
1. return `true` if one of the actual factors is less than its expected counterpart.

This approach is not compatible with PHP but avoids that an hash with stronger parameters then expected is considered weaken.  [In PHP all actual and expected factors must be equal.](https://github.com/php/php-src/blob/master/ext/standard/password.c#L300)

**Comment by phxql** [comment]
@sephiroth-j added a `needsRehash` method. Thank you vermy much! This will be part of the next released version.
