### ISSUE TITLE
Number of parallel executions

### ISSUE THREAD

**Issue by acidelk** [phxql/argon2-jvm#60]
Hi!
I have a problem.
My profiler show a big problem for me - maximum of parallel calculating hash is 4.
Can i increase this number?
I don`t understand anything?

**Comment by phxql** [comment]
Hello!

see Section 3 of the [Argon2 whitepaper](https://github.com/P-H-C/phc-winner-argon2/blob/master/argon2-specs.pdf).

Degree of parallelism p can be set from 1 to 2^24 - 1. Setting this to a higher value doesn't mean that the hash can be calculated faster. It's the opposite: If you set it from 1 to e.g. 2, the hash will consume more CPU power.

See section 9 of the mentioned whitepaper if you need help selecting Argon2 parameters.

Does this answer your question?

**Comment by acidelk** [comment]
Yep.
Thx for link on argon specification. 
I dont have any questions.
