### ISSUE TITLE
Please update to newest argon2 version

### ISSUE THREAD

**Issue by jbellic** [phxql/argon2-jvm#63]
Version 20190702 has been released, please update the lib.
Thanks for your efforts.

**Comment by phxql** [comment]
[ ] Linux x86
[ ] Linux x64
[ ] ARM
[ ] ARM 64
[ ] OSX
[ ] Windows

**Comment by phxql** [comment]
Version 2.6 of Argon2 jvm just released, which contains the newest argon2 library.
