### ISSUE TITLE
hash verify takes much time to validate the given password.

### ISSUE THREAD

**Issue by kabilan-ideas2it** [phxql/argon2-jvm#68]
Hash verify method takes 6 seconds to validate the below data.  Does can be optimize the performance of this scenario?
Method used:
Argon2Library.INSTANCE.argon2i_verify(encoded, pwd, new Size_t(pwd.length));
Parameters: 
encoded = $argon2i$v=19$m=128000,t=40,p=4$vQkUFJlLI8si5Id0YiiOUw$uTD6ge1AtvF6aseWlfdSWUft0k8Rq7l0XfE0zaPVjx0
pwd = test1234

**Comment by phxql** [comment]
Argon2 is specifically designed to be resource intensive. If you want the hash validation to be faster, lower the parameters (iterations and parallelism).
