### ISSUE TITLE
Argon2 is extremely slow on Raspberry Pi

### ISSUE THREAD

**Issue by ArgentinaSeby** [phxql/argon2-jvm#76]
I wrote a server in Java, which is hosted on my Raspberry Pi 3B.
The server takes up to 5 seconds to respond to a call, based on the hash function. 

I checked the iterations with the mentioned helper method. 
I'm using:
```
  public String hashPassword(String plainPassword) {
        char[] securedPassword = null;
        try {
            securedPassword = plainPassword.toCharArray();

            return argon2.hash(2, 20000, 2, securedPassword);
        } finally {
            argon2.wipeArray(securedPassword);
        }
    } 
```

with:

```
  SecuredPassword() {
        this.argon2 = Argon2Factory.create(Argon2Factory.Argon2Types.ARGON2i,64,128);
    }
```

The server works and responds perfectly fine without argon2. 

**Is something wrong with my parameters or is the Raspberry Pi cpu just too weak to process this ?** 

These are the specs:

- Quad Core 1.2GHz Broadcom BCM2837 64bit CPU.
- 1GB RAM.
- BCM43438 wireless LAN and Bluetooth Low Energy (BLE) on board.
- 100 Base Ethernet.
- 40-pin extended GPIO.
- 4 USB 2 ports.
- 4 Pole stereo output and composite video port.
- Full size HDMI.

**Comment by phxql** [comment]
If it takes to long, you should lower the iteration count and the parallelism (both 2 in your example).

If it still takes too long, you could try to install libargon2 from your raspi distribution - maybe they have compiled it with processor optimizations.

If it then still takes too long, the CPU is just too weak.

**Comment by phxql** [comment]
Did that solve your problem?

**Comment by ArgentinaSeby** [comment]
Yes, that helped a lot.

**Comment by phxql** [comment]
Great :)
