### ISSUE TITLE
Publish on Maven Central

### ISSUE THREAD

**Issue by bannmann** [phxql/argon2-jvm#8]
Having to include a custom repository is doable, but some people are reluctant to do so. It would be great if you could publish the library on Maven Central.

**Comment by phxql** [comment]
Published it on https://oss.sonatype.org/content/groups/public/de/mkammerer/, should soon be on Maven Central.

**Comment by PH0lder** [comment]
Must be there, as I just built and tested the code using the documented maven dependencies.
