### ISSUE TITLE
Pepper/secret implementation?

### ISSUE THREAD

**Issue by ebreeze** [phxql/argon2-jvm#83]
As far as I know Argon2 also allows a pepper in the algorithm itself, called the "secret". 
Is it possible to implemnt the setting this parameter as well?

**Comment by phxql** [comment]
Should be possible ([secret is in the context](https://github.com/P-H-C/phc-winner-argon2/blob/master/include/argon2.h#L202)) by using the `argon2*_ctx(argon2_context *context);` methods. This needs a bigger refactoring of the existing code.

**Comment by Suniastar** [comment]
I've tried to fix this issue with my recent pull request #86 as I would need support for secrets and associated data as well.
Maybe someone can take a look at it.

**Comment by phxql** [comment]
Thanks for your work, i've merged the PR!
