### ISSUE TITLE
Library is not compatible with java modules

### ISSUE THREAD

**Issue by ertong** [phxql/argon2-jvm#84]
There is no module-info.java in argon2-jvm-nolibs package.
Moreover 
`Automatic-Module-Name: de.mkammerer.argon2-nolibs`
which is invalid package name.

As a result, in order to use the library as module it should be repackaged, which is not the best thing to do.

**Comment by phxql** [comment]
This is fixed in https://github.com/phxql/argon2-jvm/issues/80 which lands in the next release.

**Comment by phxql** [comment]
Fix is released in >= 2.10.

**Comment by A248** [comment]
@phxql Would it be acceptable to PR a multi-release jar which includes `module-info` in META-INF/versions/11? There are still some benefits to having a full module descriptor (`module-info.java`) over `Automatic-Module-Name`. Creating a MRJAR would require building with JDK 11, but runtime compatibility with JDK 6 can still be maintained.

**Comment by phxql** [comment]
Yes, if you want to help to support JPMS for real, i'll be thankful :)
