### ISSUE TITLE
Date of the Release or Release-Candidate

### ISSUE THREAD

**Issue by Suniastar** [phxql/argon2-jvm#89]
I would like to use the Pepper/Secret Implementation (#83) in my project without relying on git submodules.

Can you already estimate when the next release or release candidate will be available for maven/gradle projects?

**Comment by phxql** [comment]
Hi,

ah, sorry, didn't know you were waiting on it. I will release a new version soon!

**Comment by Suniastar** [comment]
Cool thanks! But no worries I can wait a few more days ;)

**Comment by phxql** [comment]
Great! I plan to do it on the weekend on 2021-10-02/2021-10-03

**Comment by phxql** [comment]
Just released 2.11 with your changes. Might take a day to be synced to Maven Central!
