### ISSUE TITLE
Plaintext passwords stay on heap longer than necessary

### ISSUE THREAD

**Issue by bannmann** [phxql/argon2-jvm#9]
The arrays created within `hash` and `verify` should be overwritten with zeroes after use to reduce the attack window time.

Furthermore, Strings should not really be used for passwords as explained [here](http://stackoverflow.com/q/8881291/7641). `BaseArgon2` should therefore provide overloads where `password` is a `char[]` instead of `String` so the calling code may zero out their array as well. The existing methods could be deprecated to highlight this problem.

**Comment by phxql** [comment]
I've added overloads with `char[]` and updated the example in the readme to use the `char[]` overloads and the new `wipeArray` method. The versions which take the `String` now wipe their internal arrays after usage.

**Comment by GrmpCerber** [comment]
@phxql Isn't this issue mostly closed by d612 and b04b ?
In addition I would advise you to mark all prototypes using `String` input for password `@Deprecated`.
Other option, following your comment in #10 "I also decided to break compatibility" you could simply remove them and update the "major" version number (eg. "argon2-jvm:v2.0)

I can create a PR for this if you want ;)

**Comment by phxql** [comment]
Yes, that issue is mostly resolved, the only thing missing are the @Deprecated annotations. I'll add them and release a version 2.0. Just need to compile the binaries for OSX and test the damn Windows binaries.

**Comment by GrmpCerber** [comment]
Thanks 

I'll be looking forward 2.0 release.
Don't forget to give a look at #13 before releasing (or notify me of a preview version so that I check on my side)

**Comment by phxql** [comment]
Hi,

i've updated the Windows binaries in the `develop` branch. Can you please try to build the project with `./gradlew clean build`? The tests should now succeed on Windows.

**Comment by phxql** [comment]
Fixed with v2.0.
