### ISSUE TITLE
How to specify the salt value?

### ISSUE THREAD

**Issue by jpstotz** [phxql/argon2-jvm#91]
The current Argon2 interface has no method for executing Argon2 with a custom selected salt as it is needed for key derivation. 

Please provide a method that allows to specify the salt value and returns the generated `byte[]` for example:

`byte[] hash(int iterations, int memory, int parallelism, byte[] salt, byte[] data);`

**Comment by jpstotz** [comment]
Seems like this feature is a bit hidden, I finally found it:

```
Argon2Advanced argon2 = Argon2Factory.createAdvanced();
HashResult result = argon2.hashAdvanced(iterations, memory, parallelism, pwd, salt, 80, Argon2Version.V13);
```

**Comment by phxql** [comment]
If you need key derivation, you can also take a look at `de.mkammerer.argon2.Argon2Advanced#pbkdf(int, int, int, char[], java.nio.charset.Charset, byte[], int)`, which is a password based key derivation.
