### ISSUE TITLE
Java compile issues(javafx)

### ISSUE THREAD

**Issue by ThomasGustafson** [phxql/argon2-jvm#92]
I am trying to use this  module in a javafx project and I can not get it to import properly even after adding a pom.xml file with dependencies.
These imports will have the de red:

![argon2 import issues](https://user-images.githubusercontent.com/86768123/146046206-35876a20-1205-4618-8ced-2aa37ba19b20.PNG)

![maven dependancy](https://user-images.githubusercontent.com/86768123/146045909-8df2a12e-6327-4dd1-abf0-33279485b428.PNG)

any help would be greatly appreciated

Thank you for your time

Thomas Gustafson

**Comment by phxql** [comment]
Hello!

Other dependencies are working fine? This is just an issue with argon2-jvm?

**Comment by ThomasGustafson** [comment]
yes  The other libraries being used are javafx, SQLite version 3.8.9.1 but the SQLite is not actively being used yet used yet.
![argon 2 error](https://user-images.githubusercontent.com/86768123/146235355-fa3f7667-3f8c-4814-b5c3-4e5300a98e9e.PNG)
.

**Comment by phxql** [comment]
Are you using Java Module System?

**Comment by ThomasGustafson** [comment]
yes here is what I am looking at
![modules](https://user-images.githubusercontent.com/86768123/146426318-f46a3d9e-3265-4e7a-a415-4506c8e51bd9.PNG)


I got the argon2jvm from   https://repo1.maven.org/maven2/de/mkammerer/argon2-jvm/2.11/

**Comment by ThomasGustafson** [comment]
The good news is I figured out how to get the library in .
I downloaded version 2.11 nolibs  jar but I have run into one other issue with the hash method  it appears to be deprecated and I was wondering what should be used in it's place. It is also giving me a  can not be referenced from static content error.

![hash issue](https://user-images.githubusercontent.com/86768123/146440578-5199b5e2-bb19-42df-b1fd-1944b2023fe1.PNG)





Thank you for your time and any help

Thomas Gustafson

**Comment by phxql** [comment]
Please take a look at the readme here: https://github.com/phxql/argon2-jvm#usage

It shows the correct usage of argon2-jvm.

**Comment by ThomasGustafson** [comment]
This looks good aside from this method readPasswordFromUser(); it is red is there another document for what that method is supposed to do/ the code for it?

**Comment by ThomasGustafson** [comment]
version 2.11 nolibs is not working due to a java con.sun.jna.NativeLong Error 
![Native Long Error](https://user-images.githubusercontent.com/86768123/146655005-ab64cc8d-2141-430d-8edd-a678eb1d2d6e.PNG)
![ModulesbeingUsed](https://user-images.githubusercontent.com/86768123/146655006-dedd0cf4-f545-4347-92e8-c2ac86e7c036.PNG)

Any ideas?

Thank you for your time and any help

Thomas Gustafson

**Comment by ThomasGustafson** [comment]
I solved this problem  I had to add the argon2 2.11 jvm jar and the jar for jna version 5.10.0.
