### ISSUE TITLE
argon 2  verify issue with sqlite 

### ISSUE THREAD

**Issue by ThomasGustafson** [phxql/argon2-jvm#93]
I am currently working on passcode verification for my program Sound Sphere  but the verify method is not working for some reason.
I am attaching the method I use to create a user and inset into database(that works) and the methods used to get the stored hash and the one to verify it.

![add new user](https://user-images.githubusercontent.com/86768123/147835444-42ec5128-5d04-4877-872e-89b1592eceb7.PNG)
![getting password from user](https://user-images.githubusercontent.com/86768123/147835448-4579d8b9-841e-42f7-ada1-5fad8f96c50d.PNG)
![getting password from user2](https://user-images.githubusercontent.com/86768123/147835450-a7eeb2d0-b72f-4a2d-b60f-77598a5d1635.PNG)
![getStored hash](https://user-images.githubusercontent.com/86768123/147835460-85df9aa2-1e45-4253-9007-f026fd81d68e.PNG)
![hash password(verify)](https://user-images.githubusercontent.com/86768123/147835466-80f614ee-e7af-4782-8a1a-9d6ccab1c6ee.PNG)

Thank you for your time and any help 

Thomas Gustafson

p.s. the HashPassword method is triggered on an on press through fxml.

**Comment by phxql** [comment]
Hi, what is the expected vs the actual behaviour?

Btw, you can convert a String into a `char[]` by calling `.toCharArray` on the String instance. You don't need to iterate over the chars and do the copying by yourself.

**Comment by ThomasGustafson** [comment]
The expected result is for the user to enter the username and passkey and for the Program to get the stored hash(hash in database) then use the stored hash in the argon 2. Verify function.

An example would be you make a new user let's say Bob(userName) with a passcode of 12345
When the user is created the create user function will hash the password and add it to the database(this part works) then when Bob goes to log in the password is taken and converted to a char and the stored hash is selected from the database based on the username (the selecting of the hash from the database works) then with that information the program will use the argon 2. Verify  to verify the password so if Bob enters 12345 then the verify function should return true but what I get is false even when entering the correct credentials.

**Comment by phxql** [comment]
Well, I don't know where the bug in your program is. Is the code example from the argon2-jvm README working? If yes, then it's likely that this is a logic bug in your program, not in the argon2-jvm library.

**Comment by ThomasGustafson** [comment]
you are talking about the example here https://github.com/phxql/argon2-jvm/blob/master/README.md 

right?

**Comment by ThomasGustafson** [comment]
how do you strip the salt from the encoded hash that is my best guess as to what is causing the problem?

**Comment by ThomasGustafson** [comment]
I got it to work  I think the problem was I was using two different  hashing parameters for the user creation and the verification.

Thank you for your time and help.
